dependencies:
  pre:
    # update locally with:
    # openssl aes-256-cbc -e -in secret-env-plain -out secret-env-cipher -k $KEY
    - openssl aes-256-cbc -d -in secret-env-cipher -k $KEY >> ~/.circlerc
test:
  override:
    - "echo FOO: $FOO BAR: $BAR"

version: 2
general:
  branches:
    only:
      - master

jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/project

    steps:

      - checkout

      - run:
          name: Decrypt and source env vars
          command: |
            cd .circleci
            chmod +x decrypt.sh
            ./decrypt.sh
