version: 2
general:
  branches:
    only:
      - master

jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/project

    steps:

      - checkout

      - run:
          name: Decrypt and source env vars
          command: |
            cd .circleci
            chmod +x set-env-vars.sh
            ./set-env-vars.sh
