version: 2
general:
  branches:
    only:
      - master

jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/project

    steps:

      - checkout

      - run:
          name: Decrypt and source env vars
          command: |
            cd .circleci
            openssl aes-256-cbc -d -in secret-env-cipher -out secret-env-generated -md sha256 \
                -pass env:OPENSSL_PASSWORD

            source secret-env-generated

            rm secret-env-generated

            echo "FOO: ${FOO} BAR: ${BAR}"

      - run:
          name: Access env vars in another script
          command: |
            cd .circleci
            chmod +x print-env-vars.sh
            ./print-env-vars.sh
